### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by scorpio810** [rdsivd/DXFtoQET-2020#1]
Hi Ronny,
You cand send me a pull request to merge your change,

Best regards, 
Laurent

**Comment by rdsivd** [comment]
Hi Laurent,

https://github.com/rdsivd/DXFtoQET-2020

it is not clear to me what i have to do to give the pull
[cid:image001.png@01D617E3.B73F43C0]
regards

Ronny


Van: Laurent Trinques <notifications@github.com>
Verzonden: dinsdag 21 april 2020 11:08
Aan: rdsivd/DXFtoQET-2020 <DXFtoQET-2020@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [rdsivd/DXFtoQET-2020] Pull Request (#1)


Hi Ronny,
You cand send me a pull request to merge your change,

Best regards,
Laurent
